### ISSUE TITLE
LookML files in repo folders are not parsed

### ISSUE THREAD

**Issue by clausherther** [WarbyParker/lookmlint#83]
Not sure if this is an issue with the `lookml` package or `lookmlint`, but it looks like lookmlint does not scan any files in folders inside the repo.
In our Looker repo, we have views inside of subject area folders within a views folder:
- views
    - customers
    - orders
    - ...
If we move a view to the root of the repo, loomlint is able to find the file, but not inside any of the folders.

**Comment by ryantuck** [comment]
Thanks for raising @clausherther. Confirming this is an issue here, where we're simply listing files in the top-level directory, instead of recursively walking the repo.

https://github.com/WarbyParker/lookmlint/blob/d22ae3435ae356375c72b837c5a2d3eab3d1935e/lookmlint/lookml.py#L248-L256

This should be trivial to fix.

**Comment by clausherther** [comment]
@ryantuck cool, thanks! If I get some time today, I might attempt to PR this. Normally, I'd use `Path.glob` for something like this. Would you open to using Path for both `_view_file_names` and `_model_file_names`, instead of `os`?
